export const MEAL_PLANS = [
  { name: "Plant-Based Power" },
  { name: "Whole30 Week" },
  { name: "Gluten-Free Gourmet Week" },
  { name: "Clean Eating Challenge" },
  { name: "Budget-Friendly Meal Plan" },
  { name: "Vegetarian Delight" },
  { name: "Mediterranean Diet" },
  { name: "Healthy Gut Week 1" },
  { name: "Healthy Gut Week 2" },
  { name: "Healthy Gut Week 3" },
  { name: "Healthy Gut Week 4" },
  { name: "Keto Reset Week" },
  { name: "One-Pan Wonders" },
  { name: "Paleo Week 1" },
  { name: "Paleo Week 2" },
  { name: "Paleo Week 3" },
  { name: "Paleo Week 4" },
  { name: "Paleo Week 5" },
  { name: "Comfort Food Classics" },
];
