export const RECIPES = [
  {
    name: "30-Minute Chicken Stir-Fry",
    tags: ["30min", "dinner", "easy", "one-pot", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Avocado Toast",
    tags: ["breakfast", "healthy", "vegan", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Baked Salmon",
    tags: ["dinner", "easy", "gluten-free", "healthy", "high-protein", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Banana Bread",
    tags: ["breakfast", "dessert", "easy", "from:Anna", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "BBQ Pulled Pork Sandwich",
    tags: ["dinner", "easy", "from:Hugo", "one-pot"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Black Bean Tacos",
    tags: [
      "dinner",
      "easy",
      "gluten-free",
      "healthy",
      "high-protein",
      "vegan",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Blueberry Pancakes",
    tags: ["breakfast", "easy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Caesar Salad",
    tags: ["dinner", "easy", "gluten-free", "healthy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Carrot Cake",
    tags: ["dessert", "easy", "from:Anna", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Cheesy Scrambled Eggs",
    tags: ["breakfast", "easy", "high-protein", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Chicken Alfredo",
    tags: ["dinner", "easy", "from:Hugo", "one-pot", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Chicken Noodle Soup",
    tags: ["dinner", "easy", "from:Justin", "one-pot", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Chocolate Chip Cookies",
    tags: ["dessert", "easy", "from:Anna", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Clam Chowder",
    tags: [
      "dinner",
      "easy",
      "from:Justin",
      "gluten-free",
      "one-pot",
      "high-protein",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Cobb Salad",
    tags: ["lunch", "easy", "gluten-free", "healthy", "high-protein", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Cornbread",
    tags: ["dinner", "easy", "from:Hugo", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Creamy Tomato Soup",
    tags: ["lunch", "easy", "gluten-free", "healthy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Deviled Eggs",
    tags: ["snack", "easy", "high-protein", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Eggs Benedict",
    tags: ["breakfast", "easy", "high-protein", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "French Toast",
    tags: ["breakfast", "easy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Fried Rice",
    tags: [
      "dinner",
      "easy",
      "from:Hugo",
      "gluten-free",
      "one-pot",
      "high-protein",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Garlic Bread",
    tags: ["dinner", "easy", "from:Anna", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Greek Salad",
    tags: ["lunch", "easy", "gluten-free", "healthy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Grilled Cheese",
    tags: ["lunch", "easy", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Guacamole",
    tags: [
      "snack",
      "easy",
      "gluten-free",
      "healthy",
      "vegan",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Ham and Cheese Sandwich",
    tags: ["lunch", "easy", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Healthy Banana Oatmeal Cookies",
    tags: ["breakfast", "dessert", "gluten-free", "healthy", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Huevos Rancheros",
    tags: [
      "breakfast",
      "easy",
      "gluten-free",
      "high-protein",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Ice Cream Sundae",
    tags: ["dessert", "easy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Lasagna",
    tags: ["dinner", "easy", "from:Hugo", "one-pot", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Mac and Cheese",
    tags: [
      "dinner",
      "easy",
      "from:Anna",
      "gluten-free",
      "one-pot",
      "vegetarian",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Meatloaf",
    tags: ["dinner", "easy", "from:Justin", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Miso Soup",
    tags: [
      "lunch",
      "easy",
      "gluten-free",
      "healthy",
      "high-protein",
      "vegan",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Nachos",
    tags: [
      "snack",
      "easy",
      "gluten-free",
      "high-protein",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Omelette",
    tags: ["breakfast", "easy", "high-protein", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Onion Rings",
    tags: ["snack", "easy", "vegetarian", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Pad Thai",
    tags: [
      "dinner",
      "easy",
      "from:Hugo",
      "gluten-free",
      "one-pot",
      "high-protein",
      "vegan",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Pesto Pasta",
    tags: ["dinner", "easy", "gluten-free", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Potato Salad",
    tags: ["lunch", "easy", "gluten-free", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Protein Smoothie",
    tags: [
      "breakfast",
      "easy",
      "healthy",
      "high-protein",
      "vegan",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Quiche",
    tags: ["breakfast", "easy", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Ratatouille",
    tags: ["dinner", "easy", "gluten-free", "healthy", "vegan", "vegetarian"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Roast Beef",
    tags: ["dinner", "easy", "from:Justin", "high-protein"],
    cook: undefined,
    prep: undefined,
  },

  {
    name: "Chicken Lettuce Wraps",
    tags: ["dinner", "healthy", "paleo", "high-protein", "30min"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Spaghetti Squash with Meat Sauce",
    tags: ["dinner", "gluten-free", "healthy", "paleo", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Grilled Salmon with Mango Salsa",
    tags: ["dinner", "gluten-free", "healthy", "paleo", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Chicken Fajitas",
    tags: [
      "dinner",
      "gluten-free",
      "healthy",
      "paleo",
      "high-protein",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Stuffed Sweet Potatoes",
    tags: ["dinner", "gluten-free", "healthy", "paleo", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Turkey Meatballs",
    tags: ["dinner", "gluten-free", "healthy", "paleo", "high-protein"],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Beef and Broccoli Stir Fry",
    tags: [
      "dinner",
      "gluten-free",
      "healthy",
      "paleo",
      "high-protein",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Cauliflower Fried Rice",
    tags: [
      "dinner",
      "gluten-free",
      "healthy",
      "paleo",
      "vegan",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
  {
    name: "Almond Flour Pancakes",
    tags: [
      "breakfast",
      "gluten-free",
      "healthy",
      "paleo",
      "vegetarian",
      "30min",
    ],
    cook: undefined,
    prep: undefined,
  },
];
